"""adiciona coluna admin_first na timeline_preference

Revision ID: d98a84077ef3
Revises: a26549d4f779
Create Date: 2025-03-16 07:29:42.738273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd98a84077ef3'
down_revision = 'a26549d4f779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline_preference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_first', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline_preference', schema=None) as batch_op:
        batch_op.drop_column('admin_first')

    # ### end Alembic commands ###
